before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY/$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY/$CI_REGISTRY_IMAGE"
  only:
    - master
  tags:
    - docker
    - dualis

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "$CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" 
  except:
    - master
  tags:
    - docker
    - dualis
    
deploy-release:
  stage: deploy
  script:
    - cd /opt/services/dualis
    - docker-compose pull $COMPOSE_SERVICE_NAME
    - docker-compose restart $COMPOSE_SERVICE_NAME
  only:
    - master # only deploy a real release
  tags:
    - dualis
    - shell